version: "3.7"
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
      target: development
    container_name: backend
    ports:
      - "8800:8800"
      - "8801:8801"
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      target: development
    container_name: frontend
    ports:
      - "3100:3100"