version: "3.7"
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
      target: development
    container_name: backend
    hostname: backend
    ports:
      - "8800:8800"
      - "8801:8801"